### PR TITLE
Type hints and default values for Beeminder.create_datapoint and Goal.stage_datapoint

### PR DESCRIPTION
**Pull request by HaydenMacDonald**
Hi again @narthur!

I've added a couple of type hints and default values for Beeminder.create_datapoint and Goal.stage_datapoint to keep the datapoint functionality in line with the [API's required values](https://api.beeminder.com/#postdata). Let me know what you think of these changes and if acceptable, would you be able to push the changes to PyPI?

Cheers!

### CODE REVIEW

**Comment by HaydenMacDonald** [comment]
Hey @narthur, just want to make sure you see this request. Let me know if you have any thoughts/revisions!

**Comment by narthur** [comment]
@HaydenMacDonald Looks great! Sorry for the slow response. I'll deploy to PyPI asap and let you know when it's up.

**Comment by narthur** [comment]
@HaydenMacDonald It's been deployed! :)

**Comment by HaydenMacDonald** [comment]
Thanks so much @narthur!

**Pull request merged**
